export const environment = {
  production: false,
  DomainURL: "",
  DomainDestination: "",
  APIURL: "https://api.benhvien.sohu.vn/api/v1/",
  APIRootURL: "https://api.benhvien.sohu.vn/",  
  IPRegistry: "https://ipv4.myexternalip.com/json",
  IPRegistryURL: "https://api.ipregistry.co/?key=tryout",
  LoadingFile: "loading.gif",
  DialogConfigWidth: "80%",
  DialogConfigWidth60: "60%",
  InitializationString: "",
  InitializationNumber: 0,
  DanhMucUngDungID: 1,
  PageSize: 10,
  Interval: 10000,
  Number: 4,
  G: 1,
  C: 3,
  DuAnInfo: "DuAnInfo/",
  DuAnQuyetDinhInfo: "DuAnQuyetDinhInfo/",
  DuAnThuChiInfo: "DuAnThuChiInfo/",
  DanhMucBieuMauInfo: "DanhMucBieuMauInfo/",
  ThanhVienInfo: "ThanhVienInfo/",
  GoiSoInfo: "GoiSoInfo/",
  Token: "Token",
  Homepage: "Homepage",
  Login: "Login",
  Bearer: "Bearer null",
  ThanhVienToChucID: "ThanhVienToChucID",
  ThanhVienParentID: "ThanhVienParentID",
  ThanhVienID: "ThanhVienID",
  ThanhVienHoTen: "ThanhVienHoTen",
  ThanhVienTaiKhoan: "ThanhVienTaiKhoan",
  ThanhVienFileName: "ThanhVienFileName",
  UploadSuccess: "Upload thành công.",
  UploadNotSuccess: "Upload không thành công.",
  SaveSuccess: "Lưu thành công.",
  SaveNotSuccess: "Lưu không thành công.",
  DeleteConfirm: "Bạn muốn xóa dữ liệu này?",
  DeleteSuccess: "Xóa thành công.",
  DeleteNotSuccess: "Xóa không thành công.",
  LoginNotSuccess: "Đăng nhập không thành công.",
  UserNameNotExists: "Tài khoản chưa tồn tại.",
  UserNameExists: "Tài khoản đã tồn tại.",
  UserNameRequired: "UserName là bắt buộc.",
  ToChucExists: "Tổ chức đã tồn tại.",
  PageTitle: "Bệnh viện đa khoa Đồng Nai",
  PageTitleShort: "Đa khoa Đồng Nai",
  PageDescription: "Hệ sinh thái số BỆNH VIỆN ĐA KHOA ĐỒNG NAI | Chương trình chuyển đổi số quốc gia",

  IPRegistryIP: "IPRegistryIP",
  IPRegistryDevice: "IPRegistryDevice",
  IPRegistryLongitude: "IPRegistryLongitude",
  IPRegistryLatitude: "IPRegistryIPLatitude",
  IPRegistryCountryName: "IPRegistryCountryName",
  IPRegistryRegionName: "IPRegistryRegionName",
  IPRegistryCityName: "IPRegistryCityName",


};
