namespace Service_eHospital_DongNai_A.Implement
{
    public class DM_DONGIA_DEFINITIONS_LAMTRONService : BaseService<DM_DONGIA_DEFINITIONS_LAMTRON, IDM_DONGIA_DEFINITIONS_LAMTRONRepository>
    , IDM_DONGIA_DEFINITIONS_LAMTRONService
    {
    private readonly IDM_DONGIA_DEFINITIONS_LAMTRONRepository _DM_DONGIA_DEFINITIONS_LAMTRONRepository;
    public DM_DONGIA_DEFINITIONS_LAMTRONService(IDM_DONGIA_DEFINITIONS_LAMTRONRepository DM_DONGIA_DEFINITIONS_LAMTRONRepository) : base(DM_DONGIA_DEFINITIONS_LAMTRONRepository)
    {
    _DM_DONGIA_DEFINITIONS_LAMTRONRepository = DM_DONGIA_DEFINITIONS_LAMTRONRepository;
    }
    }
    }

