namespace Service_eHospital_DongNai_A.Implement
{
    public class TT_SYS_UPLOAD_LIENTHONGNHATHUOCService : BaseService<TT_SYS_UPLOAD_LIENTHONGNHATHUOC, ITT_SYS_UPLOAD_LIENTHONGNHATHUOCRepository>
    , ITT_SYS_UPLOAD_LIENTHONGNHATHUOCService
    {
    private readonly ITT_SYS_UPLOAD_LIENTHONGNHATHUOCRepository _TT_SYS_UPLOAD_LIENTHONGNHATHUOCRepository;
    public TT_SYS_UPLOAD_LIENTHONGNHATHUOCService(ITT_SYS_UPLOAD_LIENTHONGNHATHUOCRepository TT_SYS_UPLOAD_LIENTHONGNHATHUOCRepository) : base(TT_SYS_UPLOAD_LIENTHONGNHATHUOCRepository)
    {
    _TT_SYS_UPLOAD_LIENTHONGNHATHUOCRepository = TT_SYS_UPLOAD_LIENTHONGNHATHUOCRepository;
    }
    }
    }

