export const environment = {
  production: false,
  DomainURL: "",
  DomainDestination: "",
  APIURL: "http://10.84.3.124:900/api/v1/",
  APIRootURL: "http://10.84.3.124:900/",
  API_eHospital_DongNai_A_SystemURL: "http://10.84.3.124:902/api/v1/",
  API_eHospital_DongNai_A_SystemRootURL: "http://10.84.3.124:902/",
  API_eHospital_DongNai_A_DictionaryURL: "https://localhost:7085/api/v1/",
  API_eHospital_DongNai_A_DictionaryRootURL: "https://localhost:7085/",
  API_eHospital_DongNai_AURL: "https://localhost:7084/api/v1/",
  API_eHospital_DongNai_ARootURL: "https://localhost:7084/",
  API_eHospital_DongNai_A_ConfigURL: "http://10.84.3.124:905/api/v1/",
  API_eHospital_DongNai_A_ConfigRootURL: "http://10.84.3.124:905/",
  IPRegistry: "https://ipv4.myexternalip.com/json",
  IPRegistryURL: "https://api.ipregistry.co/?key=tryout",
  LoadingFile: "loading.gif",
  DialogConfigWidth: "80%",
  DialogConfigWidth60: "60%",
  InitializationString: "",
  InitializationNumber: 0,
  DanhMucUngDungID: 1,
  DanhMucTinhThanhID: 3821,
  Lst_Dictionary_TypeIDLoaiKho: 78,
  PageSize: 10,
  Interval: 10000,
  Number: 4,
  G: 1,
  C: 3,
  DuAnInfo: "DuAnInfo/",
  DuAnQuyetDinhInfo: "DuAnQuyetDinhInfo/",
  DuAnThuChiInfo: "DuAnThuChiInfo/",
  DanhMucBieuMauInfo: "DanhMucBieuMauInfo/",
  ThanhVienInfo: "ThanhVienInfo/",
  GoiSoInfo: "GoiSoInfo/",
  KhachHangInfo: "KhachHangInfo/",
  KhamSucKhoeInfo: "KhamSucKhoeInfo/",
  DMBenhNhanInfo: "DMBenhNhanInfo/",
  SysUsersInfo: "SysUsersInfo/",
  DMBangGiaInfo: "DMBangGiaInfo/",
  DMBangGiaCPHInfo: "DMBangGiaCPHInfo/",
  Download: "Download",
  PhongBan: "PhongBan",
  NhomCanLamSang: "NhomCanLamSang",
  KhoDuoc: "KhoDuoc",
  LineWidth: 3,
  MapZoom: 10,  
  Latitude: 10.9521356, 
  Longitude: 106.868, 
  MaptilerAPIKey: "6iFTqps4QVACLERa26MA",
  Token: "Token",
  Homepage: "Homepage",
  Login: "Login",
  Bearer: "Bearer null",
  ThanhVienToChucID: "ThanhVienToChucID",
  ThanhVienParentID: "ThanhVienParentID",
  ThanhVienID: "ThanhVienID",
  ThanhVienHoTen: "ThanhVienHoTen",
  ThanhVienTaiKhoan: "ThanhVienTaiKhoan",
  ThanhVienFileName: "ThanhVienFileName",
  UploadSuccess: "Upload thành công.",
  UploadNotSuccess: "Upload không thành công.",
  SaveSuccess: "Lưu thành công.",
  SaveNotSuccess: "Lưu không thành công.",
  DeleteConfirm: "Bạn muốn xóa dữ liệu này?",
  DeleteSuccess: "Xóa thành công.",
  DeleteNotSuccess: "Xóa không thành công.",
  LoginNotSuccess: "Đăng nhập không thành công.",
  UserNameNotExists: "Tài khoản chưa tồn tại.",
  UserNameExists: "Tài khoản đã tồn tại.",
  UserNameRequired: "UserName là bắt buộc.",
  ToChucExists: "Tổ chức đã tồn tại.",
  PageTitle: "Bệnh viện Đa khoa Đồng Nai",
  PageTitleShort: "Đa khoa Đồng Nai",
  PageDescription: "Hệ sinh thái số BỆNH VIỆN ĐA KHOA ĐỒNG NAI | Chương trình chuyển đổi số quốc gia",

  IPRegistryIP: "IPRegistryIP",
  IPRegistryDevice: "IPRegistryDevice",
  IPRegistryLongitude: "IPRegistryLongitude",
  IPRegistryLatitude: "IPRegistryIPLatitude",
  IPRegistryCountryName: "IPRegistryCountryName",
  IPRegistryRegionName: "IPRegistryRegionName",
  IPRegistryCityName: "IPRegistryCityName",


};
