export const environment = {
  production: false,
  DomainURL: "",
  DomainDestination: "",
  APIURL: "http://10.84.3.124:900/api/v1/",
  APIRootURL: "http://10.84.3.124:900/",
  API_eHospital_DongNai_AURL: "http://10.84.3.124:910/api/v1/",
  API_eHospital_DongNai_ARootURL: "http://10.84.3.124:910/",
  API_eHospital_DongNai_A_ConfigURL: "http://10.84.3.124:920/api/v1/",
  API_eHospital_DongNai_A_ConfigRootURL: "http://10.84.3.124:920/", 
  API_eHospital_DongNai_A_DictionaryURL: "http://10.84.3.124:930/api/v1/",
  API_eHospital_DongNai_A_DictionaryRootURL: "http://10.84.3.124:930/",   
  API_eHospital_DongNai_A_NSTLURL: "http://10.84.3.124:940/api/v1/",
  API_eHospital_DongNai_A_NSTLRootURL: "http://10.84.3.124:940/",
  API_eHospital_DongNai_A_SystemURL: "http://10.84.3.124:949/api/v1/",
  API_eHospital_DongNai_A_SystemRootURL: "http://10.84.3.124:949/",
  APIReportURL: "http://10.84.3.124:911/api/v1/",
  APIReportRootURL: "http://10.84.3.124:911/",
  IPRegistry: "https://ipv4.myexternalip.com/json",
  IPRegistryURL: "https://api.ipregistry.co/?key=tryout",
  LoadingFile: "loading.gif",
  DialogConfigWidth: "80%",
  DialogConfigWidth60: "60%",
  InitializationString: "",
  InitializationNumber: 0,
  DanhMucUngDungID: 1,
  DanhMucTinhThanhID: 3821,
  DanhMucQuanHuyenIDBienHoa: 144437,
  Lst_Dictionary_TypeIDLoaiKho: 78,
  Lst_Dictionary_TypeIDLoaiBenhAn: 66,
  Lst_Dictionary_TypeIDHinhThucDenKhamBenh: 51,
  Lst_Dictionary_TypeIDLyDoTiepNhan: 106,
  Lst_Dictionary_TypeIDTuyenKhamChuaBenh: 259,
  Lst_Dictionary_TypeIDHinhThucChuyenVien: 1333,
  Lst_Dictionary_TypeIDLyDoChuyenVien: 224,
  Lst_Dictionary_TypeIDGiaiQuyetKhamBenh: 49,
  Lst_Dictionary_TypeIDLyDoNhapVien: 67,
  Lst_Dictionary_TypeIDLyDoXuatVien: 68,
  Lst_Dictionary_TypeIDKetQuaDieuTri: 63,
  Lst_Dictionary_TypeIDMucDichChungTu: 73,
  PageSize: 10,
  Interval: 10000,
  Number: 4,
  NamBatDau: 2014,
  NamKetThuc: 2030,
  TinhThanhIDDongNai: 180,
  PhongBanIDCapCuu: 65,
  G: 1,
  C: 3,
  Logo100_26: "/image/logo100_26.png",
  Logo312_80: "/image/logo312_80.png",
  DuAnInfo: "DuAnInfo/",
  DuAnQuyetDinhInfo: "DuAnQuyetDinhInfo/",
  DuAnThuChiInfo: "DuAnThuChiInfo/",
  DanhMucBieuMauInfo: "DanhMucBieuMauInfo/",
  ThanhVienInfo: "ThanhVienInfo/",
  GoiSoInfo: "GoiSoInfo/",
  KhachHangInfo: "KhachHangInfo/",
  KhamSucKhoeInfo: "KhamSucKhoeInfo/",
  DMBenhNhanInfo: "DMBenhNhanInfo/",
  SysUsersInfo: "SysUsersInfo/",
  DMBangGiaInfo: "DMBangGiaInfo/",
  DMBangGiaCPHInfo: "DMBangGiaCPHInfo/",
  BenhAnInfo: "BenhAnInfo/",
  TiepNhanInfo: "TiepNhanInfo/",
  NSNHANVIENInfo: "NSNHANVIENInfo/",
  KhamBenhInfo: "KhamBenhInfo/",
  KhamBenhVaoVienInfo: "KhamBenhVaoVienInfo/",
  KhamBenhToaThuocInfo: "KhamBenhToaThuocInfo/",
  HRNhanVienInfo: "HRNhanVienInfo/",
  DanhMucHopDongInfo: "DanhMucHopDongInfo/",
  ThongKeInfo: "ThongKeInfo/",
  Download: "Download",
  PhongBan: "PhongBan",
  NhomCanLamSang: "NhomCanLamSang",
  KhoDuoc: "KhoDuoc",
  SoNgayDuyetThuoc: "SoNgayDuyetThuoc",
  VienPhiNgoaiTru_ThoiGianLayDanhSachChiDinh_MAX: "VienPhiNgoaiTru_ThoiGianLayDanhSachChiDinh_MAX",
  CheckBHXH: "1451;1464;1414;1397;",
  LineWidth: 3,
  MapZoom: 10,  
  Latitude: 10.9521356, 
  Longitude: 106.868, 
  MaptilerAPIKey: "6iFTqps4QVACLERa26MA",
  Token: "Token",
  Homepage: "Homepage",
  Login: "Login",
  Bearer: "Bearer null",
  ThanhVienToChucID: "ThanhVienToChucID",
  ThanhVienParentID: "ThanhVienParentID",
  ThanhVienID: "ThanhVienID",
  ThanhVienHoTen: "ThanhVienHoTen",
  ThanhVienTaiKhoan: "ThanhVienTaiKhoan",
  ThanhVienFileName: "ThanhVienFileName",
  UploadSuccess: "Upload thành công.",
  UploadNotSuccess: "Upload không thành công.",
  SaveSuccess: "Lưu thành công.",
  SaveNotSuccess: "Lưu không thành công.",
  DeleteConfirm: "Bạn muốn xóa dữ liệu này?",
  DeleteSuccess: "Xóa thành công.",
  DeleteNotSuccess: "Xóa không thành công.",
  LoginNotSuccess: "Đăng nhập không thành công.",
  UserNameNotExists: "Tài khoản chưa tồn tại.",
  UserNameExists: "Tài khoản đã tồn tại.",
  UserNameRequired: "UserName là bắt buộc.",
  ToChucExists: "Tổ chức đã tồn tại.",
  PageTitle: "Bệnh viện Đa khoa Đồng Nai",
  PageTitleShort: "Đa khoa Đồng Nai",
  PageDescription: "Hệ sinh thái số BỆNH VIỆN ĐA KHOA ĐỒNG NAI | Chương trình chuyển đổi số quốc gia",

  IPRegistryIP: "IPRegistryIP",
  IPRegistryDevice: "IPRegistryDevice",
  IPRegistryLongitude: "IPRegistryLongitude",
  IPRegistryLatitude: "IPRegistryIPLatitude",
  IPRegistryCountryName: "IPRegistryCountryName",
  IPRegistryRegionName: "IPRegistryRegionName",
  IPRegistryCityName: "IPRegistryCityName",


};
