namespace Data_eHospital_DongNai_A.Context
{
    public partial class Context : DbContext
    {
        public Context()
        {
        }
        public Context(DbContextOptions<Context>
    options)
    : base(options)
        {
        }

        public virtual DbSet<BCDP_014_TheoLo> BCDP_014_TheoLo { get; set; }
        public virtual DbSet<BCSYT_004_TinhHinhBenhTatTuVong_Bieu11_Data> BCSYT_004_TinhHinhBenhTatTuVong_Bieu11_Data { get; set; }
        public virtual DbSet<BCTH_015_HoatDongKhamBenh_Data> BCTH_015_HoatDongKhamBenh_Data { get; set; }
        public virtual DbSet<BCTH_018_DieuTri_NoiTru_Data> BCTH_018_DieuTri_NoiTru_Data { get; set; }
        public virtual DbSet<BenhAn> BenhAn { get; set; }
        public virtual DbSet<BenhAn_ChiTiet> BenhAn_ChiTiet { get; set; }
        public virtual DbSet<BenhAn_DieuTri> BenhAn_DieuTri { get; set; }
        public virtual DbSet<BenhAn_DieuTriRang> BenhAn_DieuTriRang { get; set; }
        public virtual DbSet<BenhAn_PhauThuatTrongMieng> BenhAn_PhauThuatTrongMieng { get; set; }
        public virtual DbSet<BenhAn_PhucHinhRang> BenhAn_PhucHinhRang { get; set; }
        public virtual DbSet<BenhAn_Rang> BenhAn_Rang { get; set; }
        public virtual DbSet<BenhAn_Sai_YL> BenhAn_Sai_YL { get; set; }
        public virtual DbSet<BenhAn_SaiGio> BenhAn_SaiGio { get; set; }
        public virtual DbSet<BenhAnChiTiet> BenhAnChiTiet { get; set; }
        public virtual DbSet<BenhAnNgoaiTru> BenhAnNgoaiTru { get; set; }
        public virtual DbSet<BENHANNGOAITRU_KHAMBENH> BENHANNGOAITRU_KHAMBENH { get; set; }
        public virtual DbSet<BENHANNGOAITRU_TOATHUOC> BENHANNGOAITRU_TOATHUOC { get; set; }
        public virtual DbSet<BenhAnNhiemKhuan> BenhAnNhiemKhuan { get; set; }
        public virtual DbSet<BenhAnPhauThuat> BenhAnPhauThuat { get; set; }
        public virtual DbSet<BenhAnPhauThuat_EKip> BenhAnPhauThuat_EKip { get; set; }
        public virtual DbSet<BenhAnPhauThuat_Images> BenhAnPhauThuat_Images { get; set; }
        public virtual DbSet<BenhAnPhauThuat_TamDuc> BenhAnPhauThuat_TamDuc { get; set; }
        public virtual DbSet<BenhAnPhauThuat_VTYT> BenhAnPhauThuat_VTYT { get; set; }
        public virtual DbSet<BenhAnPhauThuat_YeuCau> BenhAnPhauThuat_YeuCau { get; set; }
        public virtual DbSet<BenhAnSanKhoa> BenhAnSanKhoa { get; set; }
        public virtual DbSet<BenhAnSanKhoa_ChiTiet> BenhAnSanKhoa_ChiTiet { get; set; }
        public virtual DbSet<BenhAnTongQuat> BenhAnTongQuat { get; set; }
        public virtual DbSet<BenhAnTongQuat_CTNT> BenhAnTongQuat_CTNT { get; set; }
        public virtual DbSet<BenhAnTongQuat_CTNT_ChiTiet> BenhAnTongQuat_CTNT_ChiTiet { get; set; }
        public virtual DbSet<BenhAnTongQuat_GBT> BenhAnTongQuat_GBT { get; set; }
        public virtual DbSet<BenhAnTongQuat_GCNTT> BenhAnTongQuat_GCNTT { get; set; }
        public virtual DbSet<BenhAnTongQuat_GCS> BenhAnTongQuat_GCS { get; set; }
        public virtual DbSet<BenhAnTongQuat_GCV> BenhAnTongQuat_GCV { get; set; }
        public virtual DbSet<BenhAnTongQuat_GiayChungSinh> BenhAnTongQuat_GiayChungSinh { get; set; }
        public virtual DbSet<BenhAnTongQuat_LienQuanBenh> BenhAnTongQuat_LienQuanBenh { get; set; }
        public virtual DbSet<BenhAnTongQuat_LienQuanBenh_SanKhoa> BenhAnTongQuat_LienQuanBenh_SanKhoa { get; set; }
        public virtual DbSet<BenhAnTongQuat_Mat> BenhAnTongQuat_Mat { get; set; }
        public virtual DbSet<BenhAnTongQuat_NaoPhaThai> BenhAnTongQuat_NaoPhaThai { get; set; }
        public virtual DbSet<BenhAnTongQuat_NgoaiKhoa> BenhAnTongQuat_NgoaiKhoa { get; set; }
        public virtual DbSet<BenhAnTongQuat_NhiKhoa> BenhAnTongQuat_NhiKhoa { get; set; }
        public virtual DbSet<BenhAnTongQuat_NoiKhoa> BenhAnTongQuat_NoiKhoa { get; set; }
        public virtual DbSet<BenhAnTongQuat_PhuKhoa> BenhAnTongQuat_PhuKhoa { get; set; }
        public virtual DbSet<BenhAnTongQuat_RHM> BenhAnTongQuat_RHM { get; set; }
        public virtual DbSet<BenhAnTongQuat_SanKhoa> BenhAnTongQuat_SanKhoa { get; set; }
        public virtual DbSet<BenhAnTongQuat_SoSinh> BenhAnTongQuat_SoSinh { get; set; }
        public virtual DbSet<BenhAnTongQuat_TMH> BenhAnTongQuat_TMH { get; set; }
        public virtual DbSet<BenhAnTongQuat_TomTat> BenhAnTongQuat_TomTat { get; set; }
        public virtual DbSet<BenhAnTongQuat_TongKet> BenhAnTongQuat_TongKet { get; set; }
        public virtual DbSet<BenhAnTongQuat_TongKet_PhauThuat> BenhAnTongQuat_TongKet_PhauThuat { get; set; }
        public virtual DbSet<BenhAnTongQuat_TruyenNhiem> BenhAnTongQuat_TruyenNhiem { get; set; }
        public virtual DbSet<BenhNhan_Di_UngThuoc> BenhNhan_Di_UngThuoc { get; set; }
        public virtual DbSet<BenhNhan_HinhAnh> BenhNhan_HinhAnh { get; set; }
        public virtual DbSet<BENHNHAN_IMAGES> BENHNHAN_IMAGES { get; set; }
        public virtual DbSet<BENHNHAN_THEATM> BENHNHAN_THEATM { get; set; }
        public virtual DbSet<BenhNhan_TienCan> BenhNhan_TienCan { get; set; }
        public virtual DbSet<BHYT_Export_His> BHYT_Export_His { get; set; }
        public virtual DbSet<BHYT_KiemTra> BHYT_KiemTra { get; set; }
        public virtual DbSet<BHYT_KiemTra2> BHYT_KiemTra2 { get; set; }
        public virtual DbSet<BienBanHoiChan> BienBanHoiChan { get; set; }
        public virtual DbSet<BienBanHoiChan_Ekip> BienBanHoiChan_Ekip { get; set; }
        public virtual DbSet<BienLai> BienLai { get; set; }
        public virtual DbSet<BienLaiChiTiet> BienLaiChiTiet { get; set; }
        public virtual DbSet<c> c { get; set; }

        public virtual DbSet<CDT_DieuTriTuyenDuoi> CDT_DieuTriTuyenDuoi { get; set; }
        public virtual DbSet<CDT_KeHoachDaoTao> CDT_KeHoachDaoTao { get; set; }
        public virtual DbSet<CDT_KeHoachHoiThao_BVThamGia> CDT_KeHoachHoiThao_BVThamGia { get; set; }
        public virtual DbSet<CDT_KeHoachHoiThao_CBThamGia> CDT_KeHoachHoiThao_CBThamGia { get; set; }
        public virtual DbSet<CDT_KetQuaXuTri> CDT_KetQuaXuTri { get; set; }
        public virtual DbSet<CDT_KSK_NgoaiVien> CDT_KSK_NgoaiVien { get; set; }
        public virtual DbSet<CDT_KSK_PhanLoaiDoiTuong> CDT_KSK_PhanLoaiDoiTuong { get; set; }
        public virtual DbSet<CDT_KSK_PhanLoaiDoTuoi> CDT_KSK_PhanLoaiDoTuoi { get; set; }
        public virtual DbSet<CDT_KSK_PhanLoaiNhomBenh> CDT_KSK_PhanLoaiNhomBenh { get; set; }
        public virtual DbSet<CDT_KSK_TuyenDuoi> CDT_KSK_TuyenDuoi { get; set; }
        public virtual DbSet<CDT_KyThuatTuyenDuoi> CDT_KyThuatTuyenDuoi { get; set; }
        public virtual DbSet<CDT_LichCongTac> CDT_LichCongTac { get; set; }
        public virtual DbSet<CDT_LichCongTac_KetQua> CDT_LichCongTac_KetQua { get; set; }
        public virtual DbSet<CDT_NhanSuTuyenDuoi> CDT_NhanSuTuyenDuoi { get; set; }
        public virtual DbSet<CDT_PhanCongDeAn_1816> CDT_PhanCongDeAn_1816 { get; set; }
        public virtual DbSet<CDT_TrangThietBiTuyenDuoi> CDT_TrangThietBiTuyenDuoi { get; set; }

        public virtual DbSet<ChanDoanICD> ChanDoanICD { get; set; }
        public virtual DbSet<ChanDoanTeBaoHocCoTuCungAmDao> ChanDoanTeBaoHocCoTuCungAmDao { get; set; }
        public virtual DbSet<ChanDoanTeBaoHocCoTuCungAmDao_KetQua> ChanDoanTeBaoHocCoTuCungAmDao_KetQua { get; set; }
        public virtual DbSet<ChayThanNhanTao> ChayThanNhanTao { get; set; }
        public virtual DbSet<ChayThanNhanTao_ChiTiet> ChayThanNhanTao_ChiTiet { get; set; }
        public virtual DbSet<ChiPhiChiTiet_DoiTuong> ChiPhiChiTiet_DoiTuong { get; set; }
        public virtual DbSet<ChiPhiKCBNgoaiTru_BHYT> ChiPhiKCBNgoaiTru_BHYT { get; set; }
        public virtual DbSet<ChiPhiKCBNoiTru_BHYT> ChiPhiKCBNoiTru_BHYT { get; set; }
        public virtual DbSet<ChungTu> ChungTu { get; set; }
        public virtual DbSet<ChungTu_Report> ChungTu_Report { get; set; }
        public virtual DbSet<ChungTu_UNC> ChungTu_UNC { get; set; }
        public virtual DbSet<ChungTu_UNC_ChiTiet> ChungTu_UNC_ChiTiet { get; set; }
        public virtual DbSet<ChungTuChiPhi> ChungTuChiPhi { get; set; }
        public virtual DbSet<ChungTuChiTiet> ChungTuChiTiet { get; set; }
        public virtual DbSet<ChungTuChiTiet_Report> ChungTuChiTiet_Report { get; set; }
        public virtual DbSet<ChungTuPhanBoChiPhi> ChungTuPhanBoChiPhi { get; set; }
        public virtual DbSet<ChungTuSoLoNhap> ChungTuSoLoNhap { get; set; }
        public virtual DbSet<ChungTuSoLoNhap_Delete20230518> ChungTuSoLoNhap_Delete20230518 { get; set; }
        public virtual DbSet<ChungTuXuatBenhNhan> ChungTuXuatBenhNhan { get; set; }
        public virtual DbSet<ChungTuXuatBenhNhan_TestStent> ChungTuXuatBenhNhan_TestStent { get; set; }
        public virtual DbSet<ChuyenChungTu> ChuyenChungTu { get; set; }
        public virtual DbSet<ChuyenVien> ChuyenVien { get; set; }
        public virtual DbSet<CLSBenhPham> CLSBenhPham { get; set; }
        public virtual DbSet<CLSGhiNhanHoaChat_VTYT> CLSGhiNhanHoaChat_VTYT { get; set; }
        public virtual DbSet<CLSKetQua> CLSKetQua { get; set; }
        public virtual DbSet<CLSKetQua_DienCo> CLSKetQua_DienCo { get; set; }
        public virtual DbSet<CLSKetQua_Images> CLSKetQua_Images { get; set; }
        public virtual DbSet<CLSKetQua_SieuAmTim> CLSKetQua_SieuAmTim { get; set; }
        public virtual DbSet<CLSKetQua_Version> CLSKetQua_Version { get; set; }
        public virtual DbSet<CLSKetQua_VTYT> CLSKetQua_VTYT { get; set; }
        public virtual DbSet<CLSKetQua_XetNghiem> CLSKetQua_XetNghiem { get; set; }
        public virtual DbSet<CLSKetQua_XQ> CLSKetQua_XQ { get; set; }
        public virtual DbSet<CLSKetQuaChiTiet> CLSKetQuaChiTiet { get; set; }
        public virtual DbSet<CLSKetQuaChiTiet_His> CLSKetQuaChiTiet_His { get; set; }
        public virtual DbSet<CLSKetQuaChiTiet_Version> CLSKetQuaChiTiet_Version { get; set; }
        public virtual DbSet<CLSKetQuaKhangSinhDo> CLSKetQuaKhangSinhDo { get; set; }
        public virtual DbSet<CLSKetQuaKhangSinhDo_His> CLSKetQuaKhangSinhDo_His { get; set; }
        public virtual DbSet<CLSKetQuaMau> CLSKetQuaMau { get; set; }
        public virtual DbSet<CLSKetQuaMau_ChiTiet> CLSKetQuaMau_ChiTiet { get; set; }
        public virtual DbSet<ClsKetQuaTrungTamNghienCuu> ClsKetQuaTrungTamNghienCuu { get; set; }
        public virtual DbSet<CLSKetQuaXNHuyet_TuyDo> CLSKetQuaXNHuyet_TuyDo { get; set; }
        public virtual DbSet<CLSKetQuaXNHuyet_TuyDo_ChiTiet> CLSKetQuaXNHuyet_TuyDo_ChiTiet { get; set; }
        public virtual DbSet<CLSKetQuaYeuCau> CLSKetQuaYeuCau { get; set; }
        public virtual DbSet<CLSProcess_Data> CLSProcess_Data { get; set; }
        public virtual DbSet<CLSYeuCau> CLSYeuCau { get; set; }
        public virtual DbSet<CLSYeuCau_PACS> CLSYeuCau_PACS { get; set; }
        public virtual DbSet<CLSYeuCau_QMS> CLSYeuCau_QMS { get; set; }
        public virtual DbSet<CLSYeuCau_QMS_Log> CLSYeuCau_QMS_Log { get; set; }
        public virtual DbSet<CLSYeuCau_ThayDoi> CLSYeuCau_ThayDoi { get; set; }
        public virtual DbSet<CLSYeuCauBarCode> CLSYeuCauBarCode { get; set; }
        public virtual DbSet<CLSYeuCauChiTiet> CLSYeuCauChiTiet { get; set; }
        public virtual DbSet<ComputerName> ComputerName { get; set; }
        public virtual DbSet<CSKH_BenhNhan_GoiDichVu> CSKH_BenhNhan_GoiDichVu { get; set; }
        public virtual DbSet<CSKH_BenhNhan_GoiDichVuChiTiet> CSKH_BenhNhan_GoiDichVuChiTiet { get; set; }
        public virtual DbSet<CSKH_DM_GoiDichVu> CSKH_DM_GoiDichVu { get; set; }
        public virtual DbSet<CSKH_DM_LoaiKhachHang> CSKH_DM_LoaiKhachHang { get; set; }
        public virtual DbSet<CSKH_GoiDichVuChiTiet> CSKH_GoiDichVuChiTiet { get; set; }
        public virtual DbSet<CSKH_ThanhVien> CSKH_ThanhVien { get; set; }
        public virtual DbSet<CSKH_The> CSKH_The { get; set; }
        public virtual DbSet<CSKH_The_ChuyenDoiLoaiThanhVien> CSKH_The_ChuyenDoiLoaiThanhVien { get; set; }
        public virtual DbSet<CSKH_The_DanhSachDoiTuongKM> CSKH_The_DanhSachDoiTuongKM { get; set; }
        public virtual DbSet<CSKH_The_DoiThe> CSKH_The_DoiThe { get; set; }
        public virtual DbSet<CSKH_The_GiamGia> CSKH_The_GiamGia { get; set; }
        public virtual DbSet<CSKH_The_GiamGia_CTTronGoi> CSKH_The_GiamGia_CTTronGoi { get; set; }
        public virtual DbSet<CSKH_The_GiamGiaTheoTG> CSKH_The_GiamGiaTheoTG { get; set; }
        public virtual DbSet<CSKH_The_HoTroChiPhiNoiTru> CSKH_The_HoTroChiPhiNoiTru { get; set; }
        public virtual DbSet<CSKH_The_KhuyenMaiKSKTongQuat> CSKH_The_KhuyenMaiKSKTongQuat { get; set; }
        public virtual DbSet<CSKH_The_KhuyenMaiNapTien> CSKH_The_KhuyenMaiNapTien { get; set; }
        public virtual DbSet<CSKH_The_KhuyenMaiNguoiThan> CSKH_The_KhuyenMaiNguoiThan { get; set; }
        public virtual DbSet<CSKH_The_MienPhiLanKham> CSKH_The_MienPhiLanKham { get; set; }
        public virtual DbSet<CSKH_The_NapTien> CSKH_The_NapTien { get; set; }
        public virtual DbSet<CSKH_The_SuDungPhongCho> CSKH_The_SuDungPhongCho { get; set; }
        public virtual DbSet<CSKH_The_TangLanKham> CSKH_The_TangLanKham { get; set; }
        public virtual DbSet<CSKH_The_TangThePhu> CSKH_The_TangThePhu { get; set; }
        public virtual DbSet<CSKH_The_TangTien> CSKH_The_TangTien { get; set; }
        public virtual DbSet<CSKH_The_ThoiHanSDThe> CSKH_The_ThoiHanSDThe { get; set; }
        public virtual DbSet<cus_BacSiKham_Time> cus_BacSiKham_Time { get; set; }
        public virtual DbSet<Cus_DM_NhaThuoc> Cus_DM_NhaThuoc { get; set; }
        public virtual DbSet<Cus_DoiTac> Cus_DoiTac { get; set; }
        public virtual DbSet<Cus_DoiTac_NoiXuat> Cus_DoiTac_NoiXuat { get; set; }
        public virtual DbSet<cus_HDDT> cus_HDDT { get; set; }
        public virtual DbSet<cus_HDDT_ChiTiet> cus_HDDT_ChiTiet { get; set; }
        public virtual DbSet<CUS_Invoices> CUS_Invoices { get; set; }
        public virtual DbSet<Cus_NoiXuat> Cus_NoiXuat { get; set; }
        public virtual DbSet<cus_PhongKham_Time> cus_PhongKham_Time { get; set; }
        public virtual DbSet<CUS_Products> CUS_Products { get; set; }
        public virtual DbSet<Cust_Backup_BsCCHN> Cust_Backup_BsCCHN { get; set; }
        public virtual DbSet<CUST_DM_NhaThuocDungChung> CUST_DM_NhaThuocDungChung { get; set; }
        public virtual DbSet<CUST_DonGiaMua_SoLe> CUST_DonGiaMua_SoLe { get; set; }
        public virtual DbSet<CUST_RTF_BenhAnPT> CUST_RTF_BenhAnPT { get; set; }
        public virtual DbSet<Cust_SyncHDDT_Temp> Cust_SyncHDDT_Temp { get; set; }
        public virtual DbSet<Cust_VienPhiNoiTru_Test> Cust_VienPhiNoiTru_Test { get; set; }
        public virtual DbSet<Cust_VienPhiNoiTru_Test_Update> Cust_VienPhiNoiTru_Test_Update { get; set; }
        public virtual DbSet<Cust_VienPhiNoiTru_Test2> Cust_VienPhiNoiTru_Test2 { get; set; }
        public virtual DbSet<Cust_VienPhiNoiTru_Test2_Update> Cust_VienPhiNoiTru_Test2_Update { get; set; }
        public virtual DbSet<DangKyHoaDonVAT> DangKyHoaDonVAT { get; set; }
        public virtual DbSet<DatabaseLog> DatabaseLog { get; set; }
        public virtual DbSet<DinhNghiaTuDienVietAnh> DinhNghiaTuDienVietAnh { get; set; }
        public virtual DbSet<DM_BacSi_DichVu> DM_BacSi_DichVu { get; set; }
        public virtual DbSet<DM_BenhNhan_Notes> DM_BenhNhan_Notes { get; set; }
        public virtual DbSet<DM_BenhVienTuyenDuoi> DM_BenhVienTuyenDuoi { get; set; }
        public virtual DbSet<DM_CauHinhKetQuaXetNghiemHuyet_TuyDo> DM_CauHinhKetQuaXetNghiemHuyet_TuyDo { get; set; }
        public virtual DbSet<DM_CDT_Loai> DM_CDT_Loai { get; set; }
        public virtual DbSet<DM_CDT_PhanLoaiKetQua> DM_CDT_PhanLoaiKetQua { get; set; }
        public virtual DbSet<DM_DichVu_201603> DM_DichVu_201603 { get; set; }
        public virtual DbSet<DM_DichVu_20160330> DM_DichVu_20160330 { get; set; }
        public virtual DbSet<DM_DoiTuongCDT> DM_DoiTuongCDT { get; set; }
        public virtual DbSet<DM_DONGIA_DEFINITIONS_LAMTRON> DM_DONGIA_DEFINITIONS_LAMTRON { get; set; }
        public virtual DbSet<DM_DonViHanhChinh_20231114> DM_DonViHanhChinh_20231114 { get; set; }
        public virtual DbSet<DM_DonViHanhChinh_20240710> DM_DonViHanhChinh_20240710 { get; set; }
        public virtual DbSet<DM_DonViHanhChinh_LT> DM_DonViHanhChinh_LT { get; set; }
        public virtual DbSet<DM_DoTuoiCDT> DM_DoTuoiCDT { get; set; }
        public virtual DbSet<DM_Duoc_CanhBao> DM_Duoc_CanhBao { get; set; }
        public virtual DbSet<DM_Duoc_DungChung> DM_Duoc_DungChung { get; set; }
        public virtual DbSet<DM_DVT_ThoiGian> DM_DVT_ThoiGian { get; set; }
        public virtual DbSet<DM_HocVienNgoaiVien> DM_HocVienNgoaiVien { get; set; }
        public virtual DbSet<DM_HoiThao> DM_HoiThao { get; set; }
        public virtual DbSet<DM_ICD_Chuong_tmp> DM_ICD_Chuong_tmp { get; set; }
        public virtual DbSet<DM_ICD_Nhom_tmp> DM_ICD_Nhom_tmp { get; set; }
        public virtual DbSet<DM_ICD_tmp> DM_ICD_tmp { get; set; }
        public virtual DbSet<DM_KeHoachDaoTao> DM_KeHoachDaoTao { get; set; }
        public virtual DbSet<DM_KeHoachDeAn_1816> DM_KeHoachDeAn_1816 { get; set; }
        public virtual DbSet<DM_KetQuaMauBenh> DM_KetQuaMauBenh { get; set; }
        public virtual DbSet<DM_KyThuat> DM_KyThuat { get; set; }
        public virtual DbSet<DM_MaDuoc> DM_MaDuoc { get; set; }
        public virtual DbSet<DM_Mapping_DoiTuong_2Khu> DM_Mapping_DoiTuong_2Khu { get; set; }
        public virtual DbSet<DM_MauBenh> DM_MauBenh { get; set; }
        public virtual DbSet<DM_MauBenh_Column> DM_MauBenh_Column { get; set; }
        public virtual DbSet<DM_MauDienCo> DM_MauDienCo { get; set; }
        public virtual DbSet<DM_MauDienCo_MauBenh> DM_MauDienCo_MauBenh { get; set; }
        public virtual DbSet<DM_NgayNghiLe> DM_NgayNghiLe { get; set; }
        public virtual DbSet<DM_NhomTiemChung> DM_NhomTiemChung { get; set; }
        public virtual DbSet<DM_PhacDoDieuTri> DM_PhacDoDieuTri { get; set; }
        public virtual DbSet<DM_PhacDoDieuTri_CT> DM_PhacDoDieuTri_CT { get; set; }
        public virtual DbSet<DM_PhacDoDieuTriDichVu_CT> DM_PhacDoDieuTriDichVu_CT { get; set; }
        public virtual DbSet<DM_PhamVi> DM_PhamVi { get; set; }
        public virtual DbSet<DM_TAIKHOAN> DM_TAIKHOAN { get; set; }
        public virtual DbSet<DM_TAIKHOAN_MAP> DM_TAIKHOAN_MAP { get; set; }
        public virtual DbSet<DM_ThuocTiemChung> DM_ThuocTiemChung { get; set; }
        public virtual DbSet<DM_TrangThietBiTuyenDuoi> DM_TrangThietBiTuyenDuoi { get; set; }
        public virtual DbSet<DMDuoc> DMDuoc { get; set; }
        public virtual DbSet<DongNai_A> DongNai_A { get; set; }
        public virtual DbSet<Duoc_DonDatHang> Duoc_DonDatHang { get; set; }
        public virtual DbSet<Duoc_DonDatHangChiTiet> Duoc_DonDatHangChiTiet { get; set; }
        public virtual DbSet<Duoc_DonGiaVon> Duoc_DonGiaVon { get; set; }
        public virtual DbSet<Duoc_DuTru> Duoc_DuTru { get; set; }
        public virtual DbSet<Duoc_DuTruChiTiet> Duoc_DuTruChiTiet { get; set; }
        public virtual DbSet<Duoc_KiemKe> Duoc_KiemKe { get; set; }
        public virtual DbSet<Duoc_SoLoNhap_GiaBan> Duoc_SoLoNhap_GiaBan { get; set; }
        public virtual DbSet<Duoc_SoLoNhap_GiaBan_Delete20230518> Duoc_SoLoNhap_GiaBan_Delete20230518 { get; set; }
        public virtual DbSet<DuocGiaVon> DuocGiaVon { get; set; }
        public virtual DbSet<DuocKhoaSoChungTu> DuocKhoaSoChungTu { get; set; }
        public virtual DbSet<DuocKyTonKho> DuocKyTonKho { get; set; }
        public virtual DbSet<DuocTonDauKy> DuocTonDauKy { get; set; }
        public virtual DbSet<DuocTonDauKy_20241230> DuocTonDauKy_20241230 { get; set; }
        public virtual DbSet<DuocTonKho> DuocTonKho { get; set; }
        public virtual DbSet<DuocTonKho_20230725> DuocTonKho_20230725 { get; set; }
        public virtual DbSet<DuocTonKho_Booking> DuocTonKho_Booking { get; set; }
        public virtual DbSet<DuocTonKho_BookingNoiTru> DuocTonKho_BookingNoiTru { get; set; }
        public virtual DbSet<DuocTonKho_BookNoiTru> DuocTonKho_BookNoiTru { get; set; }
        public virtual DbSet<DuocTonKho_BookPhamVi> DuocTonKho_BookPhamVi { get; set; }
        public virtual DbSet<DuocTonKho_DuocHu> DuocTonKho_DuocHu { get; set; }
        public virtual DbSet<DuocTonKho_GioiHan> DuocTonKho_GioiHan { get; set; }
        public virtual DbSet<Eclaim_Header2348> Eclaim_Header2348 { get; set; }
        public virtual DbSet<EMR> EMR { get; set; }
        public virtual DbSet<GhiChuDuoc> GhiChuDuoc { get; set; }
        public virtual DbSet<GiaiPhauBenhSinhThiet> GiaiPhauBenhSinhThiet { get; set; }
        public virtual DbSet<GiaiPhauBenhSinhThiet_KetQua> GiaiPhauBenhSinhThiet_KetQua { get; set; }
        public virtual DbSet<GiayChungNhanKhongCungChiTra> GiayChungNhanKhongCungChiTra { get; set; }
        public virtual DbSet<GiayRaVien> GiayRaVien { get; set; }
        public virtual DbSet<Group_PB_Kios> Group_PB_Kios { get; set; }
        public virtual DbSet<HangDoi_Details_20231109> HangDoi_Details_20231109 { get; set; }
        public virtual DbSet<HangDoi_PhongBan_ChiPhi> HangDoi_PhongBan_ChiPhi { get; set; }
        public virtual DbSet<His_CSKH_BenhNhan_GoiDichVuChiTiet> His_CSKH_BenhNhan_GoiDichVuChiTiet { get; set; }
        public virtual DbSet<His_Schedule> His_Schedule { get; set; }
        public virtual DbSet<His_ScheduleDetail> His_ScheduleDetail { get; set; }
        public virtual DbSet<His_Shift> His_Shift { get; set; }
        public virtual DbSet<His_ShiftDetail> His_ShiftDetail { get; set; }
        public virtual DbSet<His_XepLich> His_XepLich { get; set; }
        public virtual DbSet<His_XepLichChiTiet> His_XepLichChiTiet { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<HOADON_PAYRESULT> HOADON_PAYRESULT { get; set; }
        public virtual DbSet<HoaDon_ThuTu> HoaDon_ThuTu { get; set; }
        public virtual DbSet<HoaDonChiTiet> HoaDonChiTiet { get; set; }
        public virtual DbSet<HoaDonTamUng> HoaDonTamUng { get; set; }
        public virtual DbSet<HoaDonVienPhi> HoaDonVienPhi { get; set; }
        public virtual DbSet<HoaDonVienPhiChiTiet> HoaDonVienPhiChiTiet { get; set; }
        public virtual DbSet<HoaDonVienPhiNoiTru> HoaDonVienPhiNoiTru { get; set; }
        public virtual DbSet<HoiChan> HoiChan { get; set; }
        public virtual DbSet<HoiChan_BenhLy> HoiChan_BenhLy { get; set; }
        public virtual DbSet<HoiChan_Ekip> HoiChan_Ekip { get; set; }
        public virtual DbSet<HoiChan_EKipMo> HoiChan_EKipMo { get; set; }
        public virtual DbSet<HoiChanPhauThuat> HoiChanPhauThuat { get; set; }
        public virtual DbSet<HoiChanPhauThuat_Ekip> HoiChanPhauThuat_Ekip { get; set; }
        public virtual DbSet<HoiChanXaTri> HoiChanXaTri { get; set; }
        public virtual DbSet<HoiChanXaTri_Ekip> HoiChanXaTri_Ekip { get; set; }
        public virtual DbSet<HoiChanXaTriTrong> HoiChanXaTriTrong { get; set; }
        public virtual DbSet<HoiChanXaTriTrong_Ekip> HoiChanXaTriTrong_Ekip { get; set; }
        public virtual DbSet<HoSoLienThongSoYTe> HoSoLienThongSoYTe { get; set; }
        public virtual DbSet<HoSoSucKhoe> HoSoSucKhoe { get; set; }
        public virtual DbSet<HoSoSucKhoe_DinhKy> HoSoSucKhoe_DinhKy { get; set; }
        public virtual DbSet<HoSoSucKhoe_DinhKy_Chitiet> HoSoSucKhoe_DinhKy_Chitiet { get; set; }
        public virtual DbSet<HoSoSucKhoe_TiemChung> HoSoSucKhoe_TiemChung { get; set; }
        public virtual DbSet<HoSoSucKhoe_TienSuBanThan> HoSoSucKhoe_TienSuBanThan { get; set; }
        public virtual DbSet<HoSoSucKhoe_TiepXuc> HoSoSucKhoe_TiepXuc { get; set; }
        public virtual DbSet<Import_DM_DonViHanhChinh> Import_DM_DonViHanhChinh { get; set; }
        public virtual DbSet<Import_DM_ICD_YHCT> Import_DM_ICD_YHCT { get; set; }
        public virtual DbSet<Import_DM_ICD_YHCT_Chuong_Nhom> Import_DM_ICD_YHCT_Chuong_Nhom { get; set; }
        public virtual DbSet<Import_Lst_Dictionary_NgheNghiep> Import_Lst_Dictionary_NgheNghiep { get; set; }
        public virtual DbSet<KhamBenh> KhamBenh { get; set; }

        public virtual DbSet<KhamBenh_ChuyenKhoa> KhamBenh_ChuyenKhoa { get; set; }
        public virtual DbSet<KhamBenh_HenTaiKham> KhamBenh_HenTaiKham { get; set; }
        public virtual DbSet<KhamBenh_ICD> KhamBenh_ICD { get; set; }
        public virtual DbSet<KhamBenh_SanPhuKhoaThai> KhamBenh_SanPhuKhoaThai { get; set; }
        public virtual DbSet<KhamBenh_SinhHieu> KhamBenh_SinhHieu { get; set; }
        public virtual DbSet<KhamBenh_ThayDoi> KhamBenh_ThayDoi { get; set; }
        public virtual DbSet<KhamBenh_TiemChung> KhamBenh_TiemChung { get; set; }
        public virtual DbSet<KhamBenh_ToaThuoc> KhamBenh_ToaThuoc { get; set; }
        public virtual DbSet<KhamBenh_VaoVien> KhamBenh_VaoVien { get; set; }
        public virtual DbSet<KhamBenh_VaoVien_SanKhoa> KhamBenh_VaoVien_SanKhoa { get; set; }
        public virtual DbSet<KhamBenh_VTYT> KhamBenh_VTYT { get; set; }
        public virtual DbSet<KhamGayMe> KhamGayMe { get; set; }
        public virtual DbSet<KhamGayMe_NguoiLon> KhamGayMe_NguoiLon { get; set; }
        public virtual DbSet<KhamGayMe_Tim> KhamGayMe_Tim { get; set; }
        public virtual DbSet<KhamGayMe_TreEm> KhamGayMe_TreEm { get; set; }
        public virtual DbSet<KhamSucKhoe> KhamSucKhoe { get; set; }
        public virtual DbSet<KhamSucKhoeChiTiet> KhamSucKhoeChiTiet { get; set; }
        public virtual DbSet<KiemDiemTuVong> KiemDiemTuVong { get; set; }
        public virtual DbSet<KiemDiemTuVong_ThanhVien> KiemDiemTuVong_ThanhVien { get; set; }
        public virtual DbSet<KSK_Congty> KSK_Congty { get; set; }
        public virtual DbSet<KSK_DM_NhomDoiTuong_DichVu> KSK_DM_NhomDoiTuong_DichVu { get; set; }
        public virtual DbSet<KSK_HopDong> KSK_HopDong { get; set; }
        public virtual DbSet<KSK_HopDong_BenhNhan> KSK_HopDong_BenhNhan { get; set; }
        public virtual DbSet<KSK_HopDong_BenhNhan_DichVu> KSK_HopDong_BenhNhan_DichVu { get; set; }
        public virtual DbSet<KSK_HopDong_DichVu> KSK_HopDong_DichVu { get; set; }
        public virtual DbSet<KSK_HopDong_GoiDichVu> KSK_HopDong_GoiDichVu { get; set; }
        public virtual DbSet<KSK_HopDong_KetQua_CL> KSK_HopDong_KetQua_CL { get; set; }
        public virtual DbSet<KSK_HopDong_KetQua_NHD_CL> KSK_HopDong_KetQua_NHD_CL { get; set; }
        public virtual DbSet<KSK_NhomDoiTuongKSK> KSK_NhomDoiTuongKSK { get; set; }
        public virtual DbSet<Lab_SIDStatus> Lab_SIDStatus { get; set; }
        public virtual DbSet<LabIQC_New> LabIQC_New { get; set; }
        public virtual DbSet<LichHen> LichHen { get; set; }
        public virtual DbSet<LichHen_BenhNhan> LichHen_BenhNhan { get; set; }
        public virtual DbSet<LichHen_His> LichHen_His { get; set; }
        public virtual DbSet<LichLamViec> LichLamViec { get; set; }
        public virtual DbSet<LichLamViecChiTiet> LichLamViecChiTiet { get; set; }
        public virtual DbSet<LienThongHoSoSucKhoe> LienThongHoSoSucKhoe { get; set; }
        public virtual DbSet<LIS_Tmp_CLSKetQuaChiTiet> LIS_Tmp_CLSKetQuaChiTiet { get; set; }
        public virtual DbSet<LIS_Tmp_CLSKetQuaChiTiet_His> LIS_Tmp_CLSKetQuaChiTiet_His { get; set; }
        public virtual DbSet<Log_UpdateInformation> Log_UpdateInformation { get; set; }
        public virtual DbSet<Lst_KeyData> Lst_KeyData { get; set; }
        public virtual DbSet<Lst_KeyData_Backup20240805> Lst_KeyData_Backup20240805 { get; set; }
        public virtual DbSet<Lst_KeyData_DichVu> Lst_KeyData_DichVu { get; set; }
        public virtual DbSet<Lst_KeyData_DuocPham> Lst_KeyData_DuocPham { get; set; }
        public virtual DbSet<Lst_KeyData_DuocPham_Backup20240805> Lst_KeyData_DuocPham_Backup20240805 { get; set; }
        public virtual DbSet<Lst_KeyData_MaBenhNhan> Lst_KeyData_MaBenhNhan { get; set; }
        public virtual DbSet<Lst_KeyData_SoThuTuTiepNhan> Lst_KeyData_SoThuTuTiepNhan { get; set; }
        public virtual DbSet<Lst_KeyData_TiepNhan> Lst_KeyData_TiepNhan { get; set; }
        public virtual DbSet<Lst_KeyData_ToaThuoc> Lst_KeyData_ToaThuoc { get; set; }
        public virtual DbSet<Lst_KeyData_VienPhi> Lst_KeyData_VienPhi { get; set; }
        public virtual DbSet<LyDoChuyenKhoa> LyDoChuyenKhoa { get; set; }
        public virtual DbSet<Map_ChuyenKhoaKham_PhongBan> Map_ChuyenKhoaKham_PhongBan { get; set; }
        public virtual DbSet<Map_PB_Group_Kios> Map_PB_Group_Kios { get; set; }
        public virtual DbSet<MauTinSMS> MauTinSMS { get; set; }
        public virtual DbSet<me_AppList> me_AppList { get; set; }
        public virtual DbSet<me_CapSo> me_CapSo { get; set; }
        public virtual DbSet<me_DM_Cua> me_DM_Cua { get; set; }
        public virtual DbSet<me_DM_MACAddress> me_DM_MACAddress { get; set; }
        public virtual DbSet<me_GiayChungNhanPhauThuat> me_GiayChungNhanPhauThuat { get; set; }
        public virtual DbSet<me_GoiSo> me_GoiSo { get; set; }
        public virtual DbSet<me_HangDoi> me_HangDoi { get; set; }
        public virtual DbSet<me_KhuVuc> me_KhuVuc { get; set; }
        public virtual DbSet<me_KhuVuc_User> me_KhuVuc_User { get; set; }
        public virtual DbSet<me_LichHen> me_LichHen { get; set; }
        public virtual DbSet<me_LichHenChiTiet> me_LichHenChiTiet { get; set; }
        public virtual DbSet<me_MAC_Mapping> me_MAC_Mapping { get; set; }
        public virtual DbSet<me_MenuList> me_MenuList { get; set; }
        public virtual DbSet<me_NguoiGioiThieu> me_NguoiGioiThieu { get; set; }
        public virtual DbSet<me_NguoiGioiThieuChiTiet> me_NguoiGioiThieuChiTiet { get; set; }
        public virtual DbSet<me_PhanQuyen> me_PhanQuyen { get; set; }
        public virtual DbSet<me_PhongBan> me_PhongBan { get; set; }
        public virtual DbSet<me_User> me_User { get; set; }
        public virtual DbSet<me_VitriCuaTrenForm> me_VitriCuaTrenForm { get; set; }
        public virtual DbSet<MienGiam> MienGiam { get; set; }
        public virtual DbSet<MienGiamChiTiet> MienGiamChiTiet { get; set; }
        public virtual DbSet<MienGiamNoiTru> MienGiamNoiTru { get; set; }
        public virtual DbSet<MienGiamNoiTruChiTiet> MienGiamNoiTruChiTiet { get; set; }
        public virtual DbSet<NghiPhep> NghiPhep { get; set; }
        public virtual DbSet<NhanVien_KSK_NgoaiVien> NhanVien_KSK_NgoaiVien { get; set; }
        public virtual DbSet<NhanVien_TTDT_1> NhanVien_TTDT_1 { get; set; }
        public virtual DbSet<NhapVien> NhapVien { get; set; }
        public virtual DbSet<NoiTru_ChamSoc> NoiTru_ChamSoc { get; set; }
        public virtual DbSet<NoiTru_ChamSocDichTruyen> NoiTru_ChamSocDichTruyen { get; set; }
        public virtual DbSet<NoiTru_ChuyenKhu> NoiTru_ChuyenKhu { get; set; }
        public virtual DbSet<NoiTru_DichVu> NoiTru_DichVu { get; set; }
        public virtual DbSet<NoiTru_GiuongBenh> NoiTru_GiuongBenh { get; set; }
        public virtual DbSet<NoiTru_KhamBenh> NoiTru_KhamBenh { get; set; }
        public virtual DbSet<NoiTru_LuuTru> NoiTru_LuuTru { get; set; }
        public virtual DbSet<NoiTru_LuuTru_Trace> NoiTru_LuuTru_Trace { get; set; }
        public virtual DbSet<NoiTru_LuuTruChiTiet> NoiTru_LuuTruChiTiet { get; set; }
        public virtual DbSet<NoiTru_NhapVien> NoiTru_NhapVien { get; set; }
        public virtual DbSet<NoiTru_ToaThuoc> NoiTru_ToaThuoc { get; set; }
        public virtual DbSet<NoiTru_TraThuoc> NoiTru_TraThuoc { get; set; }
        public virtual DbSet<NoiTru_TraThuocChiTiet> NoiTru_TraThuocChiTiet { get; set; }
        public virtual DbSet<NoiTru_TuThi> NoiTru_TuThi { get; set; }
        public virtual DbSet<ObjectsMapping> ObjectsMapping { get; set; }
        public virtual DbSet<PhacDoDieuTri_BN> PhacDoDieuTri_BN { get; set; }
        public virtual DbSet<PhieuChanDoanHoaMoMienDich> PhieuChanDoanHoaMoMienDich { get; set; }
        public virtual DbSet<PhieuDieuTri> PhieuDieuTri { get; set; }
        public virtual DbSet<PhieuGhiNhanUngThu> PhieuGhiNhanUngThu { get; set; }
        public virtual DbSet<PhieuLinhDuoc> PhieuLinhDuoc { get; set; }
        public virtual DbSet<PhieuLinhDuocChiTiet> PhieuLinhDuocChiTiet { get; set; }
        public virtual DbSet<PhieuMoPhong> PhieuMoPhong { get; set; }
        public virtual DbSet<PhieuMoPhongChiTiet> PhieuMoPhongChiTiet { get; set; }
        public virtual DbSet<PhieuSoKetDieuTri> PhieuSoKetDieuTri { get; set; }
        public virtual DbSet<PhieuXaTri> PhieuXaTri { get; set; }
        public virtual DbSet<QuanLyBenhPham> QuanLyBenhPham { get; set; }
        public virtual DbSet<QuanLyBenhPham_YeuCau> QuanLyBenhPham_YeuCau { get; set; }

        public virtual DbSet<RIS_MESSAGES_SEND> RIS_MESSAGES_SEND { get; set; }
        public virtual DbSet<RTFFiles> RTFFiles { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<ScheduleDetail> ScheduleDetail { get; set; }
        public virtual DbSet<Shift> Shift { get; set; }
        public virtual DbSet<ShiftDetail> ShiftDetail { get; set; }
        public virtual DbSet<SinhHieu> SinhHieu { get; set; }
        
        public virtual DbSet<Sync_DM_BenhNhan_KeyGeneration> Sync_DM_BenhNhan_KeyGeneration { get; set; }
        public virtual DbSet<Sync_DM_BenhNhan_KeyGeneration_Backup_040317> Sync_DM_BenhNhan_KeyGeneration_Backup_040317 { get; set; }
        public virtual DbSet<Sync_DM_KeyGeneration> Sync_DM_KeyGeneration { get; set; }
        public virtual DbSet<Sync_KeyManager> Sync_KeyManager { get; set; }
        public virtual DbSet<Sync_KeyOffline> Sync_KeyOffline { get; set; }
        public virtual DbSet<Sync_KeyOffline_Backup_040317> Sync_KeyOffline_Backup_040317 { get; set; }
        public virtual DbSet<Sync_KeyOffline_full_04032017> Sync_KeyOffline_full_04032017 { get; set; }
        public virtual DbSet<Sync_TableName_KeyGeneration> Sync_TableName_KeyGeneration { get; set; }
        public virtual DbSet<Sync_TiepNhan_KeyGeneration> Sync_TiepNhan_KeyGeneration { get; set; }
        public virtual DbSet<Sync_TransactionData_KeyGeneration> Sync_TransactionData_KeyGeneration { get; set; }
        public virtual DbSet<Sys_ErrorLog> Sys_ErrorLog { get; set; }
        public virtual DbSet<Sys_UserWorking> Sys_UserWorking { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_FK_Xref> T_FK_Xref { get; set; }
        public virtual DbSet<TaiNan> TaiNan { get; set; }
        public virtual DbSet<Temp_Id_Ref> Temp_Id_Ref { get; set; }
        public virtual DbSet<TemplatePhieuLinh> TemplatePhieuLinh { get; set; }
        public virtual DbSet<TemplatePhieuLinhChiTiet> TemplatePhieuLinhChiTiet { get; set; }
        public virtual DbSet<ThanhToanTamTinh_Tracking> ThanhToanTamTinh_Tracking { get; set; }
        public virtual DbSet<ThoiGianYCDuoi7Gio_1_T67> ThoiGianYCDuoi7Gio_1_T67 { get; set; }
        public virtual DbSet<ThongTinCapCuu> ThongTinCapCuu { get; set; }
        public virtual DbSet<ThongTinDieuTriHIV> ThongTinDieuTriHIV { get; set; }
        public virtual DbSet<ThongTinKhamSucKhoe> ThongTinKhamSucKhoe { get; set; }
        public virtual DbSet<ThongTinNghiPhep> ThongTinNghiPhep { get; set; }
        public virtual DbSet<ThucHienCheckList> ThucHienCheckList { get; set; }
        public virtual DbSet<ThucHienCheckListChiTiet> ThucHienCheckListChiTiet { get; set; }
        public virtual DbSet<ThuPhanUngThuoc> ThuPhanUngThuoc { get; set; }
        public virtual DbSet<ThuPhanUngThuocCoHai> ThuPhanUngThuocCoHai { get; set; }
        public virtual DbSet<ThuPhanUngThuocCoHai_ThuocGayNghiNgoADR> ThuPhanUngThuocCoHai_ThuocGayNghiNgoADR { get; set; }
        public virtual DbSet<ThuPhanUngThuocCoHai_ThuocSuDungDongThoi> ThuPhanUngThuocCoHai_ThuocSuDungDongThoi { get; set; }
        public virtual DbSet<TiepNhan> TiepNhan { get; set; }
        public virtual DbSet<TiepNhan_BHYT_Cu> TiepNhan_BHYT_Cu { get; set; }
        public virtual DbSet<TiepNhan_DoiTuongThayDoi> TiepNhan_DoiTuongThayDoi { get; set; }
        public virtual DbSet<TiepNhan_ThuocUngThu> TiepNhan_ThuocUngThu { get; set; }
        public virtual DbSet<TiepNhanCapCuu> TiepNhanCapCuu { get; set; }
        public virtual DbSet<TiepNhanCapCuuChiTiet> TiepNhanCapCuuChiTiet { get; set; }
        public virtual DbSet<TinSMS> TinSMS { get; set; }
        public virtual DbSet<TinSMS_LoaiTin> TinSMS_LoaiTin { get; set; }
        public virtual DbSet<ToaThuoc> ToaThuoc { get; set; }
        public virtual DbSet<ToaThuocMau> ToaThuocMau { get; set; }
        public virtual DbSet<TomTatHoSoBenhAn> TomTatHoSoBenhAn { get; set; }
        public virtual DbSet<TonKho> TonKho { get; set; }
        public virtual DbSet<trace> trace { get; set; }
        public virtual DbSet<Transfer> Transfer { get; set; }
        public virtual DbSet<Transfer_VienPhi> Transfer_VienPhi { get; set; }
        public virtual DbSet<Transfer_VienPhi_ChiTiet> Transfer_VienPhi_ChiTiet { get; set; }
        public virtual DbSet<Transfer_VienPhi_ChiTiet_Temp> Transfer_VienPhi_ChiTiet_Temp { get; set; }
        public virtual DbSet<TreSoSinh> TreSoSinh { get; set; }
        public virtual DbSet<TT_SYS_UPLOAD_LIENTHONGNHATHUOC> TT_SYS_UPLOAD_LIENTHONGNHATHUOC { get; set; }
        public virtual DbSet<UserTraKQXN> UserTraKQXN { get; set; }
        public virtual DbSet<VienPhiNoiTru> VienPhiNoiTru { get; set; }
        public virtual DbSet<VienPhiNoiTru_Loai_IDRef> VienPhiNoiTru_Loai_IDRef { get; set; }
        public virtual DbSet<VienPhiNoiTruChiTiet> VienPhiNoiTruChiTiet { get; set; }
        public virtual DbSet<VTB_NAPRUTTIEN> VTB_NAPRUTTIEN { get; set; }
        public virtual DbSet<WEB_NEWS> WEB_NEWS { get; set; }
        public virtual DbSet<WEB_NEWS_CATEGORIES> WEB_NEWS_CATEGORIES { get; set; }
        public virtual DbSet<XacNhanChiPhi> XacNhanChiPhi { get; set; }
        public virtual DbSet<XacNhanChiPhi_DEL> XacNhanChiPhi_DEL { get; set; }
        public virtual DbSet<XacNhanChiPhi_TestStent> XacNhanChiPhi_TestStent { get; set; }
        public virtual DbSet<XacNhanChiPhiBHTN> XacNhanChiPhiBHTN { get; set; }
        public virtual DbSet<XacNhanChiPhiBHTNChiTiet> XacNhanChiPhiBHTNChiTiet { get; set; }
        public virtual DbSet<XacNhanChiPhiChiTiet> XacNhanChiPhiChiTiet { get; set; }
        public virtual DbSet<XacNhanChiPhiChiTiet_TestStent> XacNhanChiPhiChiTiet_TestStent { get; set; }
        public virtual DbSet<XacNhanSuDung> XacNhanSuDung { get; set; }
        public virtual DbSet<XepLich> XepLich { get; set; }
        public virtual DbSet<XepLichMo> XepLichMo { get; set; }
        public virtual DbSet<XepLichMo_EKipMo> XepLichMo_EKipMo { get; set; }
        public virtual DbSet<XML_CheckIn_CV130> XML_CheckIn_CV130 { get; set; }
        public virtual DbSet<XML1> XML1 { get; set; }
        public virtual DbSet<XML1_CV130> XML1_CV130 { get; set; }
        public virtual DbSet<XML10_CV130> XML10_CV130 { get; set; }
        public virtual DbSet<XML11_CV130> XML11_CV130 { get; set; }
        public virtual DbSet<XML12_CV130> XML12_CV130 { get; set; }
        public virtual DbSet<XML13_CV130> XML13_CV130 { get; set; }
        public virtual DbSet<XML14_CV130> XML14_CV130 { get; set; }
        public virtual DbSet<XML15_CV130> XML15_CV130 { get; set; }
        public virtual DbSet<XML2> XML2 { get; set; }
        public virtual DbSet<XML2_CV130> XML2_CV130 { get; set; }
        public virtual DbSet<XML3> XML3 { get; set; }
        public virtual DbSet<XML3_CV130> XML3_CV130 { get; set; }
        public virtual DbSet<XML4> XML4 { get; set; }
        public virtual DbSet<XML4_CV130> XML4_CV130 { get; set; }
        public virtual DbSet<XML5> XML5 { get; set; }
        public virtual DbSet<XML5_CV130> XML5_CV130 { get; set; }
        public virtual DbSet<XML6_CV130> XML6_CV130 { get; set; }
        public virtual DbSet<XML7_CV130> XML7_CV130 { get; set; }
        public virtual DbSet<XML8_CV130> XML8_CV130 { get; set; }
        public virtual DbSet<XML9_CV130> XML9_CV130 { get; set; }
        public virtual DbSet<YTDP_KetQua> YTDP_KetQua { get; set; }
        public virtual DbSet<YTDP_KetQuaChiTiet> YTDP_KetQuaChiTiet { get; set; }
        public virtual DbSet<Z_DuTruDuoc> Z_DuTruDuoc { get; set; }
        public virtual DbSet<ztmp_BC_Mau25A_NgoaiTru> ztmp_BC_Mau25A_NgoaiTru { get; set; }
        public virtual DbSet<ztmp_BC_Mau25A_NgoaiTru_E> ztmp_BC_Mau25A_NgoaiTru_E { get; set; }
        public virtual DbSet<ztmp_BC_Mau26A_NoiTru_E> ztmp_BC_Mau26A_NoiTru_E { get; set; }
        public virtual DbSet<ztmp_BCCLS_020> ztmp_BCCLS_020 { get; set; }
        public virtual DbSet<ztmp_BCDM_006> ztmp_BCDM_006 { get; set; }
        public virtual DbSet<ztmp_BCDN_001> ztmp_BCDN_001 { get; set; }
        public virtual DbSet<ztmp_BCDP_003> ztmp_BCDP_003 { get; set; }
        public virtual DbSet<ztmp_BCDP_013> ztmp_BCDP_013 { get; set; }
        public virtual DbSet<ztmp_BCNHM_036> ztmp_BCNHM_036 { get; set; }
        public virtual DbSet<ztmp_BCQR_01> ztmp_BCQR_01 { get; set; }
        public virtual DbSet<Ztmp_BCTH_018_BenhAn_Noitru_Luutru> Ztmp_BCTH_018_BenhAn_Noitru_Luutru { get; set; }
        public virtual DbSet<Ztmp_BCTH_018_BenhAn_TongHop> Ztmp_BCTH_018_BenhAn_TongHop { get; set; }
        public virtual DbSet<ztmp_BCTN_003> ztmp_BCTN_003 { get; set; }
        public virtual DbSet<ztmp_BCTN_006> ztmp_BCTN_006 { get; set; }
        public virtual DbSet<ztmp_BCTN_009> ztmp_BCTN_009 { get; set; }
        public virtual DbSet<ztmp_BCTN_009A> ztmp_BCTN_009A { get; set; }
        public virtual DbSet<ztmp_BCTN_021100> ztmp_BCTN_021100 { get; set; }
        public virtual DbSet<ztmp_BCTN_021101> ztmp_BCTN_021101 { get; set; }
        public virtual DbSet<ztmp_BCTN_021102> ztmp_BCTN_021102 { get; set; }
        public virtual DbSet<ztmp_BCTN_040> ztmp_BCTN_040 { get; set; }
        public virtual DbSet<ztmp_BCTN_046> ztmp_BCTN_046 { get; set; }
        public virtual DbSet<ztmp_BCVP_064D> ztmp_BCVP_064D { get; set; }
        public virtual DbSet<ztmp_BHXH_CT03> ztmp_BHXH_CT03 { get; set; }
        public virtual DbSet<ztmp_BHYT_79E> ztmp_BHYT_79E { get; set; }
        public virtual DbSet<ztmp_BHYT_80> ztmp_BHYT_80 { get; set; }
        public virtual DbSet<ztmp_BHYT_RV_2019> ztmp_BHYT_RV_2019 { get; set; }
        public virtual DbSet<ztmp_CUST_BCTH_002> ztmp_CUST_BCTH_002 { get; set; }
        public virtual DbSet<ztmp_SoKhamBenh> ztmp_SoKhamBenh { get; set; }
        public virtual DbSet<zz_HDDT> zz_HDDT { get; set; }
        public virtual DbSet<zz_HDDT_Temp> zz_HDDT_Temp { get; set; }
        public virtual DbSet<zzz_BS_ERROR> zzz_BS_ERROR { get; set; }
        public virtual DbSet<zzz_BS_YLenh_A> zzz_BS_YLenh_A { get; set; }
        public virtual DbSet<zzz_BS_YLenh_B> zzz_BS_YLenh_B { get; set; }
        public virtual DbSet<zzz_CLSYeuCau> zzz_CLSYeuCau { get; set; }
        public virtual DbSet<zzz_CLSYeuCauChiTiet> zzz_CLSYeuCauChiTiet { get; set; }
        public virtual DbSet<zzz_Cust_ThamSo> zzz_Cust_ThamSo { get; set; }
        public virtual DbSet<zzz_DM_BS_BHYT> zzz_DM_BS_BHYT { get; set; }
        public virtual DbSet<zzz_DM_Duoc_20210922> zzz_DM_Duoc_20210922 { get; set; }
        public virtual DbSet<zzz_DM_Duoc_SQD> zzz_DM_Duoc_SQD { get; set; }
        public virtual DbSet<zzz_DM_KhoaPhong> zzz_DM_KhoaPhong { get; set; }
        public virtual DbSet<zzz_DM_TenDuoc_20210922> zzz_DM_TenDuoc_20210922 { get; set; }
        public virtual DbSet<Zzz_Excel_ListBN_HuyetAp> Zzz_Excel_ListBN_HuyetAp { get; set; }
        public virtual DbSet<zzz_NgoaiDanhMuc> zzz_NgoaiDanhMuc { get; set; }
        public virtual DbSet<zzz_NgoaiTru_XuatLaiXML> zzz_NgoaiTru_XuatLaiXML { get; set; }
        public virtual DbSet<zzz_NgoaiTru_XuatLaiXML_5> zzz_NgoaiTru_XuatLaiXML_5 { get; set; }
        public virtual DbSet<zzz_NgoaiTru_XuatLaiXML_6> zzz_NgoaiTru_XuatLaiXML_6 { get; set; }
        public virtual DbSet<zzz_NoiTru_XuatLaiXML> zzz_NoiTru_XuatLaiXML { get; set; }
        public virtual DbSet<zzz_NoiTru_XuatLaiXML_5> zzz_NoiTru_XuatLaiXML_5 { get; set; }
        public virtual DbSet<zzz_NoiTru_XuatLaiXML_6> zzz_NoiTru_XuatLaiXML_6 { get; set; }
        public virtual DbSet<zzz_SaiTen> zzz_SaiTen { get; set; }
        public virtual DbSet<zzz_TyLeApTran> zzz_TyLeApTran { get; set; }
        public virtual DbSet<zzz_VTYT_Mod_20210922_1000> zzz_VTYT_Mod_20210922_1000 { get; set; }
        public virtual DbSet<zzzBS_KhamTrung> zzzBS_KhamTrung { get; set; }
        public virtual DbSet<zzzDonViHanhChanhzzz> zzzDonViHanhChanhzzz { get; set; }
        public virtual DbSet<zzzNhanVien_1> zzzNhanVien_1 { get; set; }
        public virtual DbSet<zzzPhongBan> zzzPhongBan { get; set; }
        public virtual DbSet<zzzThietBi> zzzThietBi { get; set; }
        public virtual DbSet<zzzThietBi_4> zzzThietBi_4 { get; set; }
        public virtual DbSet<zzzTrangThietBi_1> zzzTrangThietBi_1 { get; set; }
        public virtual DbSet<zzzz_SoChungTu_Temp> zzzz_SoChungTu_Temp { get; set; }
        public virtual DbSet<zzzz_tmpNgheNghiep130> zzzz_tmpNgheNghiep130 { get; set; }
        public virtual DbSet<zzzzBangKe_BHYT> zzzzBangKe_BHYT { get; set; }
        public virtual DbSet<zzzzBangKe_BHYT_All> zzzzBangKe_BHYT_All { get; set; }
        public virtual DbSet<zzzzBangKe_TuChiTra> zzzzBangKe_TuChiTra { get; set; }
        public virtual DbSet<zzzzBangKe_TuChiTra_All> zzzzBangKe_TuChiTra_All { get; set; }
        public virtual DbSet<zzzzBenhAnMienGiam> zzzzBenhAnMienGiam { get; set; }
        public virtual DbSet<zzzzBenhAnMienGiam_All> zzzzBenhAnMienGiam_All { get; set; }
        public virtual DbSet<zzzzBenhAnMienGiam_temp> zzzzBenhAnMienGiam_temp { get; set; }
        public virtual DbSet<zzzzBenhAnMienGiam_Temp_All> zzzzBenhAnMienGiam_Temp_All { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(GlobalHelper.SQLServerConectionString);
            }
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

