import { Base } from "./Base.model";

export class BenhAnTongQuat_NhiKhoa extends Base{
BenhAnTongQuat_ChiTiet_Id?: number;
BenhAnTongQuat_Id?: number;
Field_1?: string;
Field_2?: number;
Field_3?: string;
Field_4?: string;
Field_5?: string;
Field_6?: string;
Field_7?: string;
Field_8?: string;
Field_9?: number;
Field_10?: string;
Field_11?: string;
Field_12?: number;
Field_13?: number;
Field_14?: number;
Field_15?: number;
Field_16?: number;
Field_17?: number;
Field_18?: string;
Field_19?: string;
Field_20?: string;
Field_21?: string;
Field_22?: string;
Field_23?: string;
Field_24?: string;
Field_25?: string;
Field_26?: string;
Field_27?: string;
Field_28?: string;
Field_29?: string;
Field_30?: string;
Field_31?: string;
Field_32?: string;
Field_33?: string;
Field_34?: string;
Field_35?: boolean;
Field_36?: boolean;
Field_37?: boolean;
Field_38?: boolean;
Field_39?: boolean;
Field_40?: boolean;
Field_41?: number;
Field_42?: boolean;
Field_43?: string;
Field_44?: string;
Field_45?: string;
Field_46?: string;
Field_47?: boolean;
Field_48?: boolean;
Field_49?: boolean;
Field_50?: string;
Field_51?: boolean;
Field_52?: boolean;
Field_53?: boolean;
Field_54?: boolean;
Field_55?: boolean;
Field_56?: boolean;
Field_57?: boolean;
Field_58?: boolean;
Field_59?: boolean;
Field_60?: string;
Field_61?: number;
Field_62?: number;
Field_63?: number;

}


